package cn.com.dhcc.footPlatform.background.dao;

import cn.com.dhcc.footPlatform.background.domain.Branch;
/**
 * 
 * @author lihang
 * @date  2016年10月26日 上午9:32:40
 * @description
 */
public interface BranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_BRANCH
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    int insert(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_BRANCH
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    int insertSelective(Branch record);
}