package cn.com.dhcc.footPlatform.background.dao;

import cn.com.dhcc.footPlatform.background.domain.Project;
/**
 * 
 * @author lihang
 * @date  2016年10月26日 上午9:32:56
 * @description
 */
public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_PROJECT
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_PROJECT
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    int insertSelective(Project record);
}