package cn.com.dhcc.footPlatform.background.domain;
/**
 * 
 * @author lihang
 * @date  2016年10月26日 上午9:33:52
 * @description
 */
public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_ROLE.ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_ROLE.MENU_ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_ROLE.USER_ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_ROLE.ID
     *
     * @return the value of WORK_ROLE.ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_ROLE.ID
     *
     * @param id the value for WORK_ROLE.ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_ROLE.MENU_ID
     *
     * @return the value of WORK_ROLE.MENU_ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_ROLE.MENU_ID
     *
     * @param menuId the value for WORK_ROLE.MENU_ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_ROLE.USER_ID
     *
     * @return the value of WORK_ROLE.USER_ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_ROLE.USER_ID
     *
     * @param userId the value for WORK_ROLE.USER_ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}