package cn.com.dhcc.footPlatform.background.domain;
/**
 * 
 * @author lihang
 * @date  2016年10月26日 上午9:34:06
 * @description
 */
public class TaskDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_TASK_DETAILS.ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_TASK_DETAILS.USER_ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_TASK_DETAILS.STATUS
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_TASK_DETAILS.ID
     *
     * @return the value of WORK_TASK_DETAILS.ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_TASK_DETAILS.ID
     *
     * @param id the value for WORK_TASK_DETAILS.ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_TASK_DETAILS.USER_ID
     *
     * @return the value of WORK_TASK_DETAILS.USER_ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_TASK_DETAILS.USER_ID
     *
     * @param userId the value for WORK_TASK_DETAILS.USER_ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_TASK_DETAILS.STATUS
     *
     * @return the value of WORK_TASK_DETAILS.STATUS
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_TASK_DETAILS.STATUS
     *
     * @param status the value for WORK_TASK_DETAILS.STATUS
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}