package cn.com.dhcc.footPlatform.background.domain;

import java.util.Date;
/**
 * 
 * @author lihang
 * @date  2016年10月26日 上午9:34:00
 * @description
 */
public class Task {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_TASK.ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_TASK.NAME
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_TASK.USER_ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_TASK.STATUS
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_TASK.NUM
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_TASK.BEGINTIME
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private Date begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_TASK.ENDTIME
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_TASK.DESCRIPTION
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_TASK.ID
     *
     * @return the value of WORK_TASK.ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_TASK.ID
     *
     * @param id the value for WORK_TASK.ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_TASK.NAME
     *
     * @return the value of WORK_TASK.NAME
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_TASK.NAME
     *
     * @param name the value for WORK_TASK.NAME
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_TASK.USER_ID
     *
     * @return the value of WORK_TASK.USER_ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_TASK.USER_ID
     *
     * @param userId the value for WORK_TASK.USER_ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_TASK.STATUS
     *
     * @return the value of WORK_TASK.STATUS
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_TASK.STATUS
     *
     * @param status the value for WORK_TASK.STATUS
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_TASK.NUM
     *
     * @return the value of WORK_TASK.NUM
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_TASK.NUM
     *
     * @param num the value for WORK_TASK.NUM
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_TASK.BEGINTIME
     *
     * @return the value of WORK_TASK.BEGINTIME
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_TASK.BEGINTIME
     *
     * @param begintime the value for WORK_TASK.BEGINTIME
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_TASK.ENDTIME
     *
     * @return the value of WORK_TASK.ENDTIME
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_TASK.ENDTIME
     *
     * @param endtime the value for WORK_TASK.ENDTIME
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_TASK.DESCRIPTION
     *
     * @return the value of WORK_TASK.DESCRIPTION
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_TASK.DESCRIPTION
     *
     * @param description the value for WORK_TASK.DESCRIPTION
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}