package cn.com.dhcc.footPlatform.background.dao;

import java.util.List;

import cn.com.dhcc.footPlatform.background.domain.Menu;
/**
 * 
 * @author lihang
 * @date  2016年10月26日 上午9:32:49
 * @description
 */
public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_MENU
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    int deleteByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_MENU
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_MENU
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_MENU
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    Menu selectByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_MENU
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_MENU
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    int updateByPrimaryKey(Menu record);
    
    /**
     * @author LMH
     * @return
     */
     List<Menu> findAll();

}