package cn.com.dhcc.footPlatform.background.dao;

import cn.com.dhcc.footPlatform.background.domain.Task;
/**
 * 
 * @author lihang
 * @date  2016年10月26日 上午9:33:14
 * @description
 */
public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_TASK
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_TASK
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    int insertSelective(Task record);
}