package cn.com.dhcc.footPlatform.background.domain;
/**
 * 
 * @author lihang
 * @date  2016年10月26日 上午9:34:27
 * @description
 */
public class TranslateKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSLATE_COL.COL_NAME
     *
     * @mbggenerated Wed Oct 26 09:28:25 CST 2016
     */
    private String colName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSLATE_COL.ITEM_NO
     *
     * @mbggenerated Wed Oct 26 09:28:25 CST 2016
     */
    private String itemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRANSLATE_COL.TAB_NAME
     *
     * @mbggenerated Wed Oct 26 09:28:25 CST 2016
     */
    private String tabName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSLATE_COL.COL_NAME
     *
     * @return the value of TRANSLATE_COL.COL_NAME
     *
     * @mbggenerated Wed Oct 26 09:28:25 CST 2016
     */
    public String getColName() {
        return colName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSLATE_COL.COL_NAME
     *
     * @param colName the value for TRANSLATE_COL.COL_NAME
     *
     * @mbggenerated Wed Oct 26 09:28:25 CST 2016
     */
    public void setColName(String colName) {
        this.colName = colName == null ? null : colName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSLATE_COL.ITEM_NO
     *
     * @return the value of TRANSLATE_COL.ITEM_NO
     *
     * @mbggenerated Wed Oct 26 09:28:25 CST 2016
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSLATE_COL.ITEM_NO
     *
     * @param itemNo the value for TRANSLATE_COL.ITEM_NO
     *
     * @mbggenerated Wed Oct 26 09:28:25 CST 2016
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo == null ? null : itemNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRANSLATE_COL.TAB_NAME
     *
     * @return the value of TRANSLATE_COL.TAB_NAME
     *
     * @mbggenerated Wed Oct 26 09:28:25 CST 2016
     */
    public String getTabName() {
        return tabName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRANSLATE_COL.TAB_NAME
     *
     * @param tabName the value for TRANSLATE_COL.TAB_NAME
     *
     * @mbggenerated Wed Oct 26 09:28:25 CST 2016
     */
    public void setTabName(String tabName) {
        this.tabName = tabName == null ? null : tabName.trim();
    }
}