package cn.com.dhcc.footPlatform.background.domain;
/**
 * 
 * @author lihang
 * @date  2016年10月26日 上午9:33:47
 * @description
 */
public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_PROJECT.ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_PROJECT.NAME
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_PROJECT.BRANCH_ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    private String branchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_PROJECT.ID
     *
     * @return the value of WORK_PROJECT.ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_PROJECT.ID
     *
     * @param id the value for WORK_PROJECT.ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_PROJECT.NAME
     *
     * @return the value of WORK_PROJECT.NAME
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_PROJECT.NAME
     *
     * @param name the value for WORK_PROJECT.NAME
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_PROJECT.BRANCH_ID
     *
     * @return the value of WORK_PROJECT.BRANCH_ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_PROJECT.BRANCH_ID
     *
     * @param branchId the value for WORK_PROJECT.BRANCH_ID
     *
     * @mbggenerated Wed Oct 26 09:28:26 CST 2016
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId == null ? null : branchId.trim();
    }
}